# Generated by Django 2.1.4 on 2018-12-17 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='pic')),
                ('index', models.IntegerField(default=0, verbose_name='order')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
            ],
            options={
                'verbose_name': 'bammer item',
                'verbose_name_plural': 'bammer item',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='unique no.')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('click_num', models.IntegerField(default=0, verbose_name='views')),
                ('sold_num', models.IntegerField(default=0, verbose_name='sales')),
                ('fav_num', models.IntegerField(default=0, verbose_name='saves')),
                ('goods_num', models.IntegerField(default=0, verbose_name='stocks')),
                ('market_price', models.FloatField(default=0, verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='shop price')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='short description')),
                ('ship_free', models.BooleanField(default=True, verbose_name='freight')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='cover page')),
                ('is_new', models.BooleanField(default=False, verbose_name='new')),
                ('is_hot', models.BooleanField(default=False, verbose_name='popular')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'item',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='category name', max_length=30, verbose_name='category name')),
                ('code', models.CharField(default='', help_text='category code', max_length=30, verbose_name='category code')),
                ('desc', models.TextField(default='', help_text='description', verbose_name='description')),
                ('category_type', models.IntegerField(choices=[(1, 'firs category'), (2, 'second category'), (3, 'third category')], help_text='category level', verbose_name='category level')),
                ('is_tab', models.BooleanField(default=False, help_text='nevigation or not', verbose_name='nevigation or not')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='brand', max_length=30, verbose_name='brand')),
                ('desc', models.TextField(default='', help_text='brand description', max_length=200, verbose_name='brand description')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'brands',
                'verbose_name_plural': 'brands',
                'db_table': 'goods_goodsbrand',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='item')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='popular word')),
                ('index', models.IntegerField(default=0, verbose_name='sorting')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
            ],
            options={
                'verbose_name': 'popular word',
                'verbose_name_plural': 'popular word',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.GoodsCategory', verbose_name='category')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods')),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisement',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='brands'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='item'),
        ),
    ]
