# Generated by Django 2.1.4 on 2018-12-17 06:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='state')),
                ('city', models.CharField(default='', max_length=100, verbose_name='city')),
                ('district', models.CharField(default='', max_length=100, verbose_name='area')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='receiver')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='phone')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('goods', models.ForeignKey(help_text='item id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saves',
                'verbose_name_plural': 'saves',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'comment'), (2, 'feedback'), (3, 'query'), (4, 'after sales'), (5, 'watching for buying')], default=1, help_text='comment type: 1(comment),2(feedback),3(query),4(after sales),5(watchong for buying)', verbose_name='comment type')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='topic')),
                ('message', models.TextField(default='', help_text='comment content', verbose_name='comment content')),
                ('file', models.FileField(help_text='uploads', upload_to='message/images/', verbose_name='uploads')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'goods')},
        ),
    ]
