# Generated by Django 2.1.4 on 2018-12-17 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='item number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order item',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Overtime'), ('WAIT_BUYER_PAY', 'Creating order'), ('TRADE_FINISHED', 'transnction finished'), ('paying', 'waiting for paying')], default='paying', max_length=30, verbose_name='status')),
                ('post_script', models.CharField(max_length=200, verbose_name='comment')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='price')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='payment time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='receiver')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='phone')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='order')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='adding time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
    ]
